# Generated by Django 2.0.1 on 2018-06-06 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0002_jenisdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='jenis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proposal.JenisDocument'),
        ),
        migrations.AddField(
            model_name='document',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10000000000, null=True),
        ),
    ]
