# Generated by Django 2.0.1 on 2018-05-31 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donatur', '0002_auto_20180531_0256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(blank=True, max_length=100, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10000000000, null=True)),
                ('donatur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donatur.Donatur')),
            ],
        ),
    ]
