# Generated by Django 2.0.1 on 2018-05-31 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donatur', '0003_donasi'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisDonasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='donasi',
            name='jenis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='donatur.JenisDonasi'),
        ),
    ]
